theme:
  colors:
    text:
      primary: "#c6d0f5"
      secondary: "#ca9ee6"
      inverted: "#232634"
      faint: "#b5bfe2"
      warning: "#e78284"
      success: "#a6d189"
    background:
      selected: "#414559"
    border:
      primary: "#ca9ee6"
      secondary: "#51576d"
      faint: "#414559"
