#!/usr/bin/env sh

have() { command -v "$1" > /dev/null 2>&1; } # Verify that a package is installed.
take() { mkdir -p "$1" && cd "$1" || return 1; } # Create a directory and change into it.
alias mkcd=take
cdf() { cd "`osascript -e 'tell app "Finder" to POSIX path of (insertion location as alias)'`"; } # Change to the frontmost Finder window directory.
whatthecommit() { curl --silent --fail https://whatthecommit.com/index.txt; }

alias cat=bat
alias ls='exa -F --git --no-icons --no-permissions --no-user -I .git'
alias ll='ls -la'
alias lst='ls --tree'
alias lsd='ls --only-dirs'
alias fd='fd --hidden'
alias mkdir='mkdir -p'
alias mk='mkdir'
alias cp='cp -i'
alias mv='mv -i'
alias cl='clear'
alias dev='cd $XDG_DEV_DIR'

# Git aliases.
alias pull='git pull origin'
alias push='git push origin'
alias commit='git commit -m'
alias add='git add'
alias status='git status'

# Shortcuts.
alias uppercase='tr "[:lower:]" "[:upper:]"'
alias lowercase='tr "[:upper:]" "[:lower:]"'
alias reload='source ${ZDOTDIR:-$HOME}/.zshrc'

# Other
alias urldecode='python3 -c "import sys, urllib.parse as ul; \
    print(ul.unquote_plus(sys.argv[1]))"'
alias urlencode='python3 -c "import sys, urllib.parse as ul; \
    print (ul.quote_plus(sys.argv[1]))"'
alias serve='npx @11ty/eleventy-dev-server'
alias fdcatppuccin="rg -i -l '(latte|frapp[eé]|mocha|macchiato)' ~/.config/*"

# OS X specific aliases.
alias showfiles="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hidefiles="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"
alias disable_dsstore="defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true"
alias enable_dsstore="defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool false"
alias rm_dsstore="fd -H '^\.DS_Store$' -tf -X rm"

alias stfu="osascript -e 'set volume output muted true'"
alias pumpitup="osascript -e 'set volume output volume 100'"

alias update="brew update; brew upgrade; brew cleanup --prune=all; softwareupdate -i -a --verbose;"
alias emptytrash="sudo rm -rfv ~/.Trash"