#!/usr/bin/env sh
# 
# ~/.config/sh/profile - sh/bash/zsh profile.

# Load environment variables.
[ -f ~/.config/sh/env ] && . ~/.config/sh/env

eval "$(/opt/homebrew/bin/brew shellenv)"
export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"

eval "$(pyenv init -)"

paths=(
    "$PYENV_ROOT/bin"
    "$(brew --prefix ccache)/libexec"
    "$GOPATH/bin"
    "$CARGO_HOME/bin"
    "$PNPM_HOME"
    "$XDG_BIN_HOME"
    "$XDG_SCRIPT_DIR"
)
for p in "${paths[@]}"; do
    case ":${PATH}:" in
        *:"$p":*)
            ;;
        *)
            export PATH="$p:$PATH"
            ;;
    esac
done