#!/usr/bin/env zsh

if ! command -v gdate &> /dev/null; then
    echo "gdate is not installed"
    exit 1
fi

if [[ $# -ne 1 ]]; then
    echo "Usage: $0 <timestamp>"
    exit 1
fi

echo $(gdate -d @"$1" "+%B %d, %Y %T")