name: Install

on:
  push:

jobs:
  install:
    runs-on: macos-latest
    steps:
      - name: Install
        run: curl -fsSL https://github.com/uncenter/dotfiles/raw/main/install.sh | sh

      - name: Check
        run: |
          ls -lA $HOME
          pnpm list --global
          fnm list
